window.esdocSearchIndex = [
  [
    "redux-xforms/createbykey.js~createbykey",
    "function/index.html#static-function-createByKey",
    "<span>createByKey</span> <span class=\"search-result-import-path\">redux-xforms/createByKey.js</span>",
    "function"
  ],
  [
    "redux-xforms/createbykey.js~creategetbykey",
    "function/index.html#static-function-createGetByKey",
    "<span>createGetByKey</span> <span class=\"search-result-import-path\">redux-xforms/createByKey.js</span>",
    "function"
  ],
  [
    "redux-xforms/createreducersbykey.js~createreducersbykey",
    "function/index.html#static-function-createReducersByKey",
    "<span>createReducersByKey</span> <span class=\"search-result-import-path\">redux-xforms/createReducersByKey.js</span>",
    "function"
  ],
  [
    "redux-xforms/expandreducertokeys.js~expandreducertokeys",
    "function/index.html#static-function-expandReducerToKeys",
    "<span>expandReducerToKeys</span> <span class=\"search-result-import-path\">redux-xforms/expandReducerToKeys.js</span>",
    "function"
  ],
  [
    "redux-xforms/isolateslice.js~isolateslice",
    "function/index.html#static-function-isolateSlice",
    "<span>isolateSlice</span> <span class=\"search-result-import-path\">redux-xforms/isolateSlice.js</span>",
    "function"
  ],
  [
    "redux-xforms/transformreducers.js~transformreducers",
    "function/index.html#static-function-transformReducers",
    "<span>transformReducers</span> <span class=\"search-result-import-path\">redux-xforms/transformReducers.js</span>",
    "function"
  ],
  [
    "redux-xforms/updateslice.js~updateslice",
    "function/index.html#static-function-updateSlice",
    "<span>updateSlice</span> <span class=\"search-result-import-path\">redux-xforms/updateSlice.js</span>",
    "function"
  ],
  [
    "redux-xforms/withfilter.js~withfilter",
    "function/index.html#static-function-withFilter",
    "<span>withFilter</span> <span class=\"search-result-import-path\">redux-xforms/withFilter.js</span>",
    "function"
  ],
  [
    "redux-xforms/withinitialstate.js~withinitialstate",
    "function/index.html#static-function-withInitialState",
    "<span>withInitialState</span> <span class=\"search-result-import-path\">redux-xforms/withInitialState.js</span>",
    "function"
  ],
  [
    "redux-xforms/witholdstateifequal.js~witholdstateifequal",
    "function/index.html#static-function-withOldStateIfEqual",
    "<span>withOldStateIfEqual</span> <span class=\"search-result-import-path\">redux-xforms/withOldStateIfEqual.js</span>",
    "function"
  ],
  [
    "redux-xforms/withreducer.js~withreducer",
    "function/index.html#static-function-withReducer",
    "<span>withReducer</span> <span class=\"search-result-import-path\">redux-xforms/withReducer.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber3",
    "Higher order reducers for filters",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber4",
    "Higher order reducers for filters example",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber28",
    "Higher order reducers for filters simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber31",
    "Higher order reducers for filters simple reducer createReducersByFilterName",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber48",
    "Higher order reducers for filters simple reducer createReducersByFilterName should handle a single filter",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber70",
    "Higher order reducers for filters simple reducer createReducersByFilterName should handle two filters and initial state",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber37",
    "Higher order reducers for filters simple reducer createReducersByFilterName should have initial state",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber91",
    "Higher order reducers for filters simple reducer different mapActionToKey",
    "test"
  ],
  [
    "",
    "test-file/src/createReducersByKey.spec.js.html#lineNumber92",
    "Higher order reducers for filters simple reducer different mapActionToKey should handle a different different mapActionToKey",
    "test"
  ],
  [
    "",
    "test-file/src/createByKey.spec.js.html#lineNumber3",
    "createByKey",
    "test"
  ],
  [
    "",
    "test-file/src/createByKey.spec.js.html#lineNumber4",
    "createByKey should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/createByKey.spec.js.html#lineNumber17",
    "createByKey simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/createByKey.spec.js.html#lineNumber29",
    "createByKey simple reducer should create a simple byKey reducer",
    "test"
  ],
  [
    "",
    "test-file/src/createByKey.spec.js.html#lineNumber25",
    "createByKey simple reducer should have initial global state",
    "test"
  ],
  [
    "",
    "test-file/src/expandReducerToKeys.spec.js.html#lineNumber5",
    "expandReducerToKeys",
    "test"
  ],
  [
    "",
    "test-file/src/expandReducerToKeys.spec.js.html#lineNumber6",
    "expandReducerToKeys example",
    "test"
  ],
  [
    "",
    "test-file/src/expandReducerToKeys.spec.js.html#lineNumber7",
    "expandReducerToKeys example should expand a reducer to two keys",
    "test"
  ],
  [
    "",
    "test-file/src/expandReducerToKeys.spec.js.html#lineNumber22",
    "expandReducerToKeys simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/expandReducerToKeys.spec.js.html#lineNumber23",
    "expandReducerToKeys simple reducer should work with combineReducers",
    "test"
  ],
  [
    "",
    "test-file/src/isolateSlice.spec.js.html#lineNumber3",
    "isolateSlice",
    "test"
  ],
  [
    "",
    "test-file/src/isolateSlice.spec.js.html#lineNumber4",
    "isolateSlice should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/isolateSlice.spec.js.html#lineNumber17",
    "isolateSlice simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/isolateSlice.spec.js.html#lineNumber26",
    "isolateSlice simple reducer should skip actions where predicate returns false",
    "test"
  ],
  [
    "src/createbykey.js",
    "file/src/createByKey.js.html",
    "src/createByKey.js",
    "file"
  ],
  [
    "src/createbykey.spec.js",
    "test-file/src/createByKey.spec.js.html",
    "src/createByKey.spec.js",
    "testFile"
  ],
  [
    "src/createbykey.spec.js",
    "file/src/createByKey.spec.js.html",
    "src/createByKey.spec.js",
    "file"
  ],
  [
    "src/createreducersbykey.js",
    "file/src/createReducersByKey.js.html",
    "src/createReducersByKey.js",
    "file"
  ],
  [
    "src/createreducersbykey.spec.js",
    "file/src/createReducersByKey.spec.js.html",
    "src/createReducersByKey.spec.js",
    "file"
  ],
  [
    "src/createreducersbykey.spec.js",
    "test-file/src/createReducersByKey.spec.js.html",
    "src/createReducersByKey.spec.js",
    "testFile"
  ],
  [
    "src/expandreducertokeys.js",
    "file/src/expandReducerToKeys.js.html",
    "src/expandReducerToKeys.js",
    "file"
  ],
  [
    "src/expandreducertokeys.spec.js",
    "test-file/src/expandReducerToKeys.spec.js.html",
    "src/expandReducerToKeys.spec.js",
    "testFile"
  ],
  [
    "src/expandreducertokeys.spec.js",
    "file/src/expandReducerToKeys.spec.js.html",
    "src/expandReducerToKeys.spec.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/isolateslice.js",
    "file/src/isolateSlice.js.html",
    "src/isolateSlice.js",
    "file"
  ],
  [
    "src/isolateslice.spec.js",
    "test-file/src/isolateSlice.spec.js.html",
    "src/isolateSlice.spec.js",
    "testFile"
  ],
  [
    "src/isolateslice.spec.js",
    "file/src/isolateSlice.spec.js.html",
    "src/isolateSlice.spec.js",
    "file"
  ],
  [
    "src/transformreducers.js",
    "file/src/transformReducers.js.html",
    "src/transformReducers.js",
    "file"
  ],
  [
    "src/transformreducers.spec.js",
    "file/src/transformReducers.spec.js.html",
    "src/transformReducers.spec.js",
    "file"
  ],
  [
    "src/transformreducers.spec.js",
    "test-file/src/transformReducers.spec.js.html",
    "src/transformReducers.spec.js",
    "testFile"
  ],
  [
    "src/updateslice.js",
    "file/src/updateSlice.js.html",
    "src/updateSlice.js",
    "file"
  ],
  [
    "src/updateslice.spec.js",
    "test-file/src/updateSlice.spec.js.html",
    "src/updateSlice.spec.js",
    "testFile"
  ],
  [
    "src/updateslice.spec.js",
    "file/src/updateSlice.spec.js.html",
    "src/updateSlice.spec.js",
    "file"
  ],
  [
    "src/withfilter.js",
    "file/src/withFilter.js.html",
    "src/withFilter.js",
    "file"
  ],
  [
    "src/withfilter.spec.js",
    "test-file/src/withFilter.spec.js.html",
    "src/withFilter.spec.js",
    "testFile"
  ],
  [
    "src/withfilter.spec.js",
    "file/src/withFilter.spec.js.html",
    "src/withFilter.spec.js",
    "file"
  ],
  [
    "src/withinitialstate.js",
    "file/src/withInitialState.js.html",
    "src/withInitialState.js",
    "file"
  ],
  [
    "src/withinitialstate.spec.js",
    "file/src/withInitialState.spec.js.html",
    "src/withInitialState.spec.js",
    "file"
  ],
  [
    "src/withinitialstate.spec.js",
    "test-file/src/withInitialState.spec.js.html",
    "src/withInitialState.spec.js",
    "testFile"
  ],
  [
    "src/witholdstateifequal.js",
    "file/src/withOldStateIfEqual.js.html",
    "src/withOldStateIfEqual.js",
    "file"
  ],
  [
    "src/witholdstateifequal.spec.js",
    "file/src/withOldStateIfEqual.spec.js.html",
    "src/withOldStateIfEqual.spec.js",
    "file"
  ],
  [
    "src/witholdstateifequal.spec.js",
    "test-file/src/withOldStateIfEqual.spec.js.html",
    "src/withOldStateIfEqual.spec.js",
    "testFile"
  ],
  [
    "src/withreducer.js",
    "file/src/withReducer.js.html",
    "src/withReducer.js",
    "file"
  ],
  [
    "src/withreducer.spec.js",
    "file/src/withReducer.spec.js.html",
    "src/withReducer.spec.js",
    "file"
  ],
  [
    "src/withreducer.spec.js",
    "test-file/src/withReducer.spec.js.html",
    "src/withReducer.spec.js",
    "testFile"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber5",
    "transformReducers",
    "test"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber6",
    "transformReducers example",
    "test"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber7",
    "transformReducers example should handle a two filters with one enhancer",
    "test"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber32",
    "transformReducers simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber34",
    "transformReducers simple reducer should work with combineReducers",
    "test"
  ],
  [
    "",
    "test-file/src/transformReducers.spec.js.html#lineNumber52",
    "transformReducers simple reducer should work with createReducersByKey",
    "test"
  ],
  [
    "",
    "test-file/src/updateSlice.spec.js.html#lineNumber3",
    "updateSlice",
    "test"
  ],
  [
    "",
    "test-file/src/updateSlice.spec.js.html#lineNumber4",
    "updateSlice should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/updateSlice.spec.js.html#lineNumber29",
    "updateSlice simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/updateSlice.spec.js.html#lineNumber32",
    "updateSlice simple reducer should update the slice with key from action",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber3",
    "withFilter",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber5",
    "withFilter should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber19",
    "withFilter simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber24",
    "withFilter simple reducer match payload",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber28",
    "withFilter simple reducer match payload should return initial state",
    "test"
  ],
  [
    "",
    "test-file/src/withFilter.spec.js.html#lineNumber32",
    "withFilter simple reducer match payload should skip actions where predicate returns false",
    "test"
  ],
  [
    "",
    "test-file/src/withInitialState.spec.js.html#lineNumber3",
    "withInitialState",
    "test"
  ],
  [
    "",
    "test-file/src/withInitialState.spec.js.html#lineNumber4",
    "withInitialState should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/withInitialState.spec.js.html#lineNumber17",
    "withInitialState simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/withInitialState.spec.js.html#lineNumber24",
    "withInitialState simple reducer should inject initial state",
    "test"
  ],
  [
    "",
    "test-file/src/withInitialState.spec.js.html#lineNumber28",
    "withInitialState simple reducer should update state when reducer returns new state",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber3",
    "withOldStateIfEqual",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber5",
    "withOldStateIfEqual should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber21",
    "withOldStateIfEqual simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber26",
    "withOldStateIfEqual simple reducer compare payloads",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber30",
    "withOldStateIfEqual simple reducer compare payloads should return initial state",
    "test"
  ],
  [
    "",
    "test-file/src/withOldStateIfEqual.spec.js.html#lineNumber34",
    "withOldStateIfEqual simple reducer compare payloads should use the old state when comparison returns true",
    "test"
  ],
  [
    "",
    "test-file/src/withReducer.spec.js.html#lineNumber3",
    "withReducer",
    "test"
  ],
  [
    "",
    "test-file/src/withReducer.spec.js.html#lineNumber4",
    "withReducer should work as in the example",
    "test"
  ],
  [
    "",
    "test-file/src/withReducer.spec.js.html#lineNumber21",
    "withReducer simple reducer",
    "test"
  ],
  [
    "",
    "test-file/src/withReducer.spec.js.html#lineNumber30",
    "withReducer simple reducer should return the slice with nested payload",
    "test"
  ]
]